version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3307"
      - "DB_HOST=database"

  # The Web Server
  web:
    image: nginx:1.10
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3307:3307"

volumes:
  dbdata:
